name: "ssh deploy"
description: "NodeJS action for FAST deployment with rsync/ssh"
author: "easingthemes"
inputs:
  SSH_PRIVATE_KEY: # Private Key
    description: "Private Key"
    required: true
  REMOTE_HOST:
    description: "Remote host"
    required: true
  REMOTE_USER:
    description: "Remote user"
    required: true
  REMOTE_PORT:
    description: "Remote port"
    required: false
    default: "22"
  SOURCE:
    description: "Source directory"
    required: false
    default: ""
  TARGET:
    description: "Target directory"
    required: false
    default: "/home/REMOTE_USER/"
  ARGS:
    description: "Arguments to pass to rsync"
    required: false
    default: "-rltgoDzvO"
  SSH_CMD_ARGS:
    description: "An array of ssh arguments, they must be prefixed with -o and separated by a comma, for example: -o SomeArgument=no, -o SomeOtherArgument=5 "
    required: false
    default: "-o StrictHostKeyChecking=no"
  EXCLUDE:
    description: "An array of folder to exclude"
    required: false
    default: ""
  SCRIPT_BEFORE:
    description: "Script to run on host machine before rsync"
    required: false
    default: "echo 'Before rsync'"
  SCRIPT_AFTER:
    description: "Script to run on host machine after rsync"
    required: false
    default: "echo 'After rsync'"
outputs:
  status:
    description: "Status"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  color: "green"
  icon: "truck"
